export const products = [
    {
        _id: '1',
        name: 'Airpods Wireless Bluetooth Headphones',
        description: 'bluetooth technology lets',
        image: '/images/airpods.jpg',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 2,
    },
    {
        _id: '2',
        name: 'Cannon EOS 80d DSLR Camera',
        image: '/images/camera.jpg',
        description: 'bluetooth technology lets',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 0,
        rating: 5,
        numReviews: 4,
    },
    {
        _id: '3',
        name: 'iPhone 11 Pro',
        image: '/images/phone.jpg',
        description: 'bluetooth technology lets',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '4',
        name: 'Amazon Wireless Bluetooth Headphones',
        image: '/images/alexa.jpg',
        description: 'bluetooth technology lets',
        brand: 'Apple',
        category: 'Electronics',
        price: 29.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '5',
        name: 'Sony Playstation 4 Pro White Version',
        image: '/images/playstation.jpg',
        description: 'bluetooth technology lets',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 0.5,
        numReviews: 4,
    },
    {
        _id: '6',
        name: 'Logitech G-Series Gaming Mouse',
        image: '/images/mouse.jpg',
        description: 'bluetooth technology lets',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 2.5,
        numReviews: 4,
    },
]
